[package]
name = "clock"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.24"
eframe = "0.24"
rodio = "0.17"

time = { version = "0.3", features = ["local-offset"] }
